services:
  ansible:
    build: .
    container_name: ansible-controller
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ansible:/ansible
    networks:
      - app_network
    tty: true
    stdin_open: true
    command: sh -c "while true; do sleep 1; done"
    user: root
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  app_container:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: app-container
    volumes:
      - ./app:/app
      - app_artifacts:/app/dist
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  app_artifacts:
