---
- name: Install nginx
  apk:
    name: nginx
    state: present

- name: Create nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Start nginx service
  service:
    name: nginx
    state: started
    enabled: yes
